// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA27aPclLaenJuT4Pt33AIWIJgcStD0Qec',
    appId: '1:303932271291:web:b38e4c7c546f2c94e4979e',
    messagingSenderId: '303932271291',
    projectId: 'cmsc23-user-jcmalahito',
    authDomain: 'cmsc23-user-jcmalahito.firebaseapp.com',
    storageBucket: 'cmsc23-user-jcmalahito.appspot.com',
    measurementId: 'G-N8F4KYCG3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJ-KjcQHgPg6wnceJ3RMsyt7HJeDofvQ',
    appId: '1:303932271291:android:9dc391908a0b1696e4979e',
    messagingSenderId: '303932271291',
    projectId: 'cmsc23-user-jcmalahito',
    storageBucket: 'cmsc23-user-jcmalahito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBq9pCjZwwT9n2GdOKKtIm6PDP1caFlE',
    appId: '1:303932271291:ios:fcbc6ea5828c6c91e4979e',
    messagingSenderId: '303932271291',
    projectId: 'cmsc23-user-jcmalahito',
    storageBucket: 'cmsc23-user-jcmalahito.appspot.com',
    iosClientId: '303932271291-fmkkd6d92qeldo9d6onnfkfh8nq3vp65.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBq9pCjZwwT9n2GdOKKtIm6PDP1caFlE',
    appId: '1:303932271291:ios:fcbc6ea5828c6c91e4979e',
    messagingSenderId: '303932271291',
    projectId: 'cmsc23-user-jcmalahito',
    storageBucket: 'cmsc23-user-jcmalahito.appspot.com',
    iosClientId: '303932271291-fmkkd6d92qeldo9d6onnfkfh8nq3vp65.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
